import { Outfit } from "next/font/google";
import ConvexClientProvider from './ConvexClientProvider';
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const outfit = Outfit({ subsets: ['latin'] })

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={outfit.className}
      >
        <ConvexClientProvider>
          {children}
        </ConvexClientProvider>

      </body>
    </html>
  );
}
